FROM node:18-alpine

# Create app directory
WORKDIR /app

# Set timezone
ENV TZ=Asia/Bangkok
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY package*.json ./

RUN yarn cache clean && yarn 

# Bundle app source
COPY . .

EXPOSE 3000